### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by dantman** [elado/lodash-bound#2]
Are there any plans to maintain this?

There haven't been commits in awhile and the obsolete es2015 babel plugin is still being used.

To my knowledge this is the only way to use lodash in the most optimal way (function bind syntax).

**Comment by elado** [comment]
Since `::` proposal didn't make it to ES, I haven't updated this project.
At this stage, the pipeline operator seems like a better bet - https://github.com/tc39/proposal-pipeline-operator

es2015 is only used to compile this library before test/sending to npm, so it should not affect you.

Anyway, PRs welcome.

**Comment by dantman** [comment]
Sadly on top of being not as nice syntax (it's gets close but not perfect with the additional partials proposal) at the moment the pipeline operator seems to be even less stable than function bind.

I guess I'll just have to revert to plain lodash for now in new projects and hope pipeline gets stable before any of them need a long chain.
